#!/usr/bin/env bash

set -e

# Set graphviz path
export PATH=${BUILD_DIR}/heroku-buildpack-graphviz/usr/bin:${PATH}
export GRAPHVIZ_DOT=${BUILD_DIR}/heroku-buildpack-graphviz/usr/bin/dot
export LD_LIBRARY_PATH=${BUILD_DIR}/heroku-buildpack-graphviz/usr/lib:${BUILD_DIR}/.heroku/vendor/lib/:${LD_LIBRARY_PATH}

# All requirements of wsgi.py
pip install static

# Needed to serve the application (Procfile)
pip install waitress

if [[ ! -f ${BUILD_DIR}/docs/requirements.txt ]]; then
  echo "docs/requirements.txt not found"
  echo "installing Sphinx"
  pip install -q Sphinx
else
  pip install -r ${BUILD_DIR}/docs/requirements.txt
fi;

# Get sphinx build-dir
echo -e "\necho-build-dir:\n\t@echo '\$(BUILDDIR)'\n" >> ${BUILD_DIR}/docs/Makefile
(cd ${BUILD_DIR}/docs && make echo-build-dir > ${BUILD_DIR}/docs/.build-dir)

# Build Sphinx documentation
(cd ${BUILD_DIR}/docs && make html)
