#!/usr/bin/env bash

set -e

# Set graphviz path
PATH=/app/graphviz/bin:$PATH

# All requirements of wsgi.py
pip install static

# Needed to serve the application (Procfile)
pip install waitress

if [[ ! -f ${BUILD_DIR}/docs/requirements.txt ]]; then
  echo "docs/requirements.txt not found"
  echo "installing Sphinx"
  pip install -q Sphinx
else
  pip install -r ${BUILD_DIR}/docs/requirements.txt
fi;

# Build Sphinx documentation
(cd ${BUILD_DIR}/docs && make html)
